insert into Team(id, name) values (0, 'A Team')
insert into Employee(id, name, surname, teamId) values (0, 'John', 'Smith', 0)
insert into Employee(id, name, surname, teamId) values (1, 'Giuseppe', 'Smith', 0)
insert into Employee(id, name, surname, teamId) values (2, 'Gianni', 'Smith', 0)
insert into Manager(id, name, surname, teamId) values (0, 'Geeno', 'Smith', 0)
