insert into Team(id, name) values (0, 'A Team')
insert into Manager(id, name, surname, teamId) values (0, 'Serena', 'Dramis', 0)
insert into Employee(id, name, surname, teamId) values (0, 'Giorgio', 'Dramis', 0)
insert into Employee(id, name, surname, teamId) values (1, 'Bianca', 'Buzzi', 0)
insert into Employee(id, name, surname, teamId) values (2, 'Ettore', 'Dramis', 0)
